# Generated by Django 3.0.8 on 2020-08-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('bitrix_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDepthLevel_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('depthlevel', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Категория уровень 1',
                'verbose_name_plural': 'Категории уровень 1',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDepthLevel_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('depthlevel', models.IntegerField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_parent_id_lvl_2', to='catalog.CategoryDepthLevel_1', verbose_name='parent_id')),
            ],
            options={
                'verbose_name': 'Категория уровень 2',
                'verbose_name_plural': 'Категории уровень 2',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantus_id', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=1024)),
                ('oem_list', models.CharField(max_length=255)),
                ('nomenclature_code', models.CharField(max_length=255)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='catalog.Brand', verbose_name='brand_id')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDepthLevel_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('depthlevel', models.IntegerField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_parent_id_lvl_3', to='catalog.CategoryDepthLevel_2', verbose_name='parent_id')),
            ],
            options={
                'verbose_name': 'Категория уровень 3',
                'verbose_name_plural': 'Категории уровень 3',
                'ordering': ['-id', 'name'],
            },
        ),
    ]
