# Generated by Django 3.0.8 on 2020-08-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydepthlevel_2',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='categorydepthlevel_3',
            name='parent_id',
        ),
        migrations.DeleteModel(
            name='CategoryDepthLevel_1',
        ),
        migrations.DeleteModel(
            name='CategoryDepthLevel_2',
        ),
        migrations.DeleteModel(
            name='CategoryDepthLevel_3',
        ),
    ]
