# Generated by Django 3.0.8 on 2020-08-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('bitrix_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantus_id', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=1024)),
                ('oem_list', models.CharField(max_length=255)),
                ('nomenclature_code', models.CharField(max_length=255)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_id', to='catalog.Brand', verbose_name='brand_id')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-id', 'name'],
            },
        ),
    ]
