# Generated by Django 3.0.8 on 2020-08-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200812_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='lol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand'),
        ),
    ]
