# Generated by Django 3.0.8 on 2020-08-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_genre_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
