# Generated by Django 3.0.8 on 2020-08-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200813_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
