# Generated by Django 3.0.8 on 2020-08-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200813_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantus_id', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('sku', models.CharField(max_length=255)),
                ('oem_list', models.CharField(max_length=255)),
                ('nomenclature_code', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('parent_product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductCategory')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
