# Generated by Django 3.0.8 on 2020-08-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200813_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDel',
        ),
    ]
