# Generated by Django 3.0.8 on 2020-08-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200813_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
