# Generated by Django 3.0.8 on 2020-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_productcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
