# Generated by Django 3.0.8 on 2020-08-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200813_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_product_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(to='catalog.ProductCategory'),
        ),
    ]
