# Generated by Django 3.0.8 on 2020-08-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200813_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
