# Generated by Django 3.0.8 on 2020-08-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200813_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
