# Generated by Django 3.0.8 on 2020-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200813_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ManyToManyField(related_name='category_product', to='catalog.ProductCategory'),
        ),
    ]
