# Generated by Django 3.0.8 on 2020-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200813_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='products',
            field=models.ManyToManyField(related_name='category_products', to='catalog.Product'),
        ),
    ]
