# Generated by Django 3.0.8 on 2020-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200813_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_related', to='catalog.ProductCategory'),
        ),
    ]
