# Generated by Django 3.0.8 on 2020-08-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_categorytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTest',
        ),
    ]
