# Generated by Django 3.0.8 on 2020-08-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_applicabilities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicabilities',
            new_name='ProductApplicabilities',
        ),
        migrations.AlterModelOptions(
            name='productapplicabilities',
            options={'ordering': ['-id', 'name'], 'verbose_name': 'Применимость', 'verbose_name_plural': 'Применимости'},
        ),
    ]
