# Generated by Django 3.0.8 on 2020-08-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20200819_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('productapplicabilities', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_logo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BrandsImagesСertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_certificate', to='catalog.Brands')),
            ],
        ),
        migrations.CreateModel(
            name='BrandsImagesPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_photo', to='catalog.Brands')),
            ],
        ),
    ]
