# Generated by Django 3.0.8 on 2020-08-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20200821_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandsImagesСertificate',
        ),
    ]
