# Generated by Django 3.0.8 on 2020-08-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_brandsimagecertificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='productapplicabilities',
            new_name='applicabilities',
        ),
    ]
