# Generated by Django 3.0.8 on 2020-08-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20200821_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
