# Generated by Django 3.0.8 on 2020-07-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=100, verbose_name='Название')),
                ('product_img', models.CharField(max_length=300)),
                ('product_manufacture', models.CharField(max_length=100)),
                ('product_articul', models.CharField(max_length=100)),
                ('product_oem', models.CharField(max_length=300)),
                ('product_price', models.CharField(max_length=10)),
                ('product_quantity', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Популярный товар',
                'verbose_name_plural': 'Популярные товары',
                'ordering': ['product_id', 'product_name'],
            },
        ),
    ]
