# Generated by Django 3.0.8 on 2020-07-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlcore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory2',
            new_name='NewsCategory',
        ),
    ]
