# Generated by Django 3.0.8 on 2020-07-31 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlcore', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='controlcore.NewsCategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
