# Generated by Django 3.0.8 on 2020-07-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcore', '0004_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=30, verbose_name='auth.User'),
        ),
    ]
