# Generated by Django 3.0.8 on 2020-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcore', '0010_auto_20200731_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
