# Generated by Django 3.0.8 on 2020-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcore', '0015_auto_20200805_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
