# Generated by Django 3.0.8 on 2020-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcore', '0017_auto_20200805_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
