# Generated by Django 3.0.8 on 2020-08-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlcore', '0021_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
